### PR TITLE
Added standard subvolumes

### PR DESCRIPTION
**Pull request by shundhammer**
See also https://github.com/yast/yast-installation-control/pull/22

### CODE REVIEW

**Comment by shundhammer** [comment]
Notice that Travis fails because it doesn't have the new XML schema yet.

**Comment by imobachgs** [comment]
LGTM

**Comment by imobachgs** [comment]
Oh, wait, I miss version/changes update.

**Comment by shundhammer** [comment]
Superseded by https://github.com/yast/skelcd-control-SLES/pull/75

**Pull request closed without merging**
