### PR TITLE
Feature/bring back lost changes

### PR DESCRIPTION
**Pull request by dgdavid**
## Problem

Previous PR (#123) _lost_ some changes introduced directly in the package not following the usual workflow. That is, without included them in the repo :cry: 

## Solution

Bring  those changes, originally introduced by @lkocman.

## More information

https://build.suse.de/request/show/194285

### CODE REVIEW

**Comment by dgdavid** [comment]
@lkocman, @darix, friendly ping :wink:

**Comment by lslezak** [comment]
@dgdavid I think you should just copy the original changes from https://build.suse.de/package/show/SUSE:SLE-12-SP5:GA/skelcd-control-SLES and then add your new change.

This PR changes the history in the .changes file, the release managers might reject the SR.

**Comment by lslezak** [comment]
@lkocman please notice [this big warning](https://github.com/yast/skelcd-control-SLES/blob/SLE-12-SP5/package/skelcd-control-SLES.spec#L19-L28) the .spec file

**Comment by dgdavid** [comment]
Thanks @lslezak

**Pull request merged**
