### PR TITLE
Delay autoupgrade self update

### PR DESCRIPTION
**Pull request by imobach**
Fixes second part of [bsc#984656](https://bugzilla.suse.com/show_bug.cgi?id=984656).

### CODE REVIEW

**Comment by mvidner** [comment]
So the point "after packager is initialized" differs between various modes of installation like this?

mode | packager initialized after
--- | ---
installation | system_analysis
update | system_analysis
autoinstallation | autoinit
autoupgrade | autoinit

If that is correct then LGTM.

**Comment by imobach** [comment]
It's a little bit tricky. It looks like if an AutoYaST profile is defined, `system_analysis` and `update_partition_auto` [are disabled](https://github.com/yast/yast-installation/blob/57f377dec11106a3d3d8ff018a46664070d1a056/src/include/installation/inst_inc_all.rb#L158). If a profile is not set (AFAIK it's not mandatory when doing an autoupgrade), they're not disabled.

So the "common" point is after `autoinit`. Note also that during _autoinstallation_, `system_analysis` and `update_partition_auto` are not part of the workflow.

**Comment by mvidner** [comment]
I see. Just making sure we haven't overlooked something.
LGTM.

**Comment by imobach** [comment]
Thanks. Anyway it was a good exercise to find out the reason :)

**Pull request merged**
